# config.yml

# backend:
#   name: git-gateway
#   branch: master # Branch to update (optional; defaults to master)

backend:
  name: github
  repo: lukeplausin/my-static-blog
  branch: master

media_folder: 'assets/'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'blog/content/posts/'
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Slug (url)", name: "slug", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
