# config.yml

# backend:
#   name: git-gateway
#   branch: master # Branch to update (optional; defaults to master)
site_url: https://luke.plaus.in

backend:
  name: github
  repo: lukeplausin/my-static-blog
  branch: master

media_folder: 'blog/static/assets/'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'blog/content/posts/'
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Slug (url)", name: "slug", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}

      - {label: "Allow comments", name: "comment", widget: "boolean"}
      - {label: "Draft", name: "draft", widget: "boolean"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Categories", name: "categories", widget: "list"}

      - {label: "Body", name: "body", widget: "markdown"}
